#Portfolio.destroy_all
Stock.destroy_all
#Portstock.destroy_all

# port1 = Portfolio.create(name: "test 1", cash: 100000)
# port2 = Portfolio.create(name: "test 2", cash: 100000)
# port3 = Portfolio.create(name: "test 3", cash: 100000)

# google = Stock.create(name: "Google", symbol: "GOOGL", price: 1800)
# amazon = Stock.create(name: "Amazon", symbol: "AMZN", price: 1500)
# apple = Stock.create(name: "Apple", symbol: "APPL", price: 1208)
# tesla = Stock.create(name: "Tesla", symbol: "TSLA", price: 539)
# roku = Stock.create(name: "Roku", symbol: "ROKU", price: 63)


# Portstock.create(stock_id: google.id, portfolio_id: port1.id, shares: 50, purchase_price: 100)
# Portstock.create(stock_id: amazon.id, portfolio_id: port2.id, shares: 40, purchase_price: 100)
# Portstock.create(stock_id: apple.id, portfolio_id: port3.id, shares: 20, purchase_price: 100)
# Portstock.create(stock_id: tesla.id, portfolio_id: port1.id, shares: 700, purchase_price: 100)
# Portstock.create(stock_id: roku.id, portfolio_id: port2.id, shares: 9999, purchase_price: 100)

# Stock.create(name: "Activision Blizzard Inc"	          ,symbol: "ATVI"	    ,price: 54.99)
# Stock.create(name: "Adobe Inc"	                          ,symbol: "ADBE"	    ,price: 303.03)
# Stock.create(name: "Advanced Micro Devices Inc"	          ,symbol: "AMD"	    ,price: 39.62)
# Stock.create(name: "Align Technology Inc"	              ,symbol: "ALGN"	    ,price: 274.53)
# Stock.create(name: "Alexion Pharmaceuticals Inc"	      ,symbol: "ALXN"	    ,price: 107.42)
# Stock.create(name: "Amazon.com Inc"	                      ,symbol: "AMZN"	    ,price: 1740.48)
# Stock.create(name: "Amgen Inc"	                          ,symbol: "AMGN"	    ,price: 233.41)
# Stock.create(name: "American Airlines Group Inc"	      ,symbol: "AAL"	    ,price: 27.24)
# Stock.create(name: "Analog Devices Inc"	                  ,symbol: "ADI"	    ,price: 113.43)
# Stock.create(name: "Apple Inc"	                          ,symbol: "AAPL"	    ,price: 265.58)
# Stock.create(name: "Applied Materials Inc"	              ,symbol: "AMAT"	    ,price: 55.84)
# Stock.create(name: "ASML Holding NV"	                  ,symbol: "ASML"	    ,price: 273.84)
# Stock.create(name: "Autodesk Inc"	                      ,symbol: "ADSK"	    ,price: 176.63)
# Stock.create(name: "Automatic Data Processing Inc"	      ,symbol: "ADP"        ,price: 168.36)
# Stock.create(name: "Broadcom Inc"	                      ,symbol: "AVGO"	    ,price: 311.19)
# Stock.create(name: "Baidu Inc"	                          ,symbol: "BIDU"	    ,price: 116.75)
# Stock.create(name: "Biogen Inc"	                          ,symbol: "BIIB"	    ,price: 299.39)
# Stock.create(name: "Biomarin Pharmaceutical Inc"	      ,symbol: "BMRN"	    ,price: 80.08)
# Stock.create(name: "Cadence Design Systems Inc"	          ,symbol: "CDNS"	    ,price: 65.81)
# Stock.create(name: "Cerner Corp"	                      ,symbol: "CERN"	    ,price: 70.77)
# Stock.create(name: "Check Point Software Technologies Ltd",symbol:	"CHKP"	    ,price: 113.31)
# Stock.create(name: "Charter Communications Inc"	          ,symbol: "CHTR"	    ,price: 467.27)
# Stock.create(name: "Trip.com Group Ltd"	                  ,symbol: "TCOM"	    ,price: 32.22)
# Stock.create(name: "Cintas Corp"	                      ,symbol: "CTAS"	    ,price: 254.7)
# Stock.create(name: "Cisco Systems Inc"	                  ,symbol: "CSCO"	    ,price: 43.52)
# Stock.create(name: "Citrix Systems Inc"	                  ,symbol: "CTXS"	    ,price: 110.78)
# Stock.create(name: "Comcast Corp"	                      ,symbol: "CMCSA"	    ,price: 44.04)
# Stock.create(name: "Costco Wholesale Corp"	              ,symbol: "COST"	    ,price: 293.1)
# Stock.create(name: "CSX Corp"	                          ,symbol: "CSX"        ,price: 70.65)
# Stock.create(name: "Cognizant Technology Solutions Corp"  ,symbol:	"CTSH"	    ,price: 62.21)
# Stock.create(name: "Dollar Tree Inc"                      ,symbol: "DLTR"	    ,price: 90.8)
# Stock.create(name: "Electronic Arts"	                  ,symbol: "EA"         ,price: 102.12)
# Stock.create(name: "eBay Inc"	                          ,symbol: "EBAY"	    ,price: 34.79)
# Stock.create(name: "Expedia Group Inc"	                  ,symbol: "EXPE"	    ,price: 105.68)
# Stock.create(name: "Fastenal Co"	                      ,symbol: "FAST"	    ,price: 35.28)
# Stock.create(name: "Facebook"	                          ,symbol: "FB"         ,price: 199.36)
# Stock.create(name: "Fiserv Inc"	                          ,symbol: "FISV"	    ,price: 114.79)
# Stock.create(name: "Gilead Sciences Inc"	              ,symbol: "GILD"	    ,price: 65.93)
# Stock.create(name: "Alphabet Class C"	                  ,symbol: "GOOG"	    ,price: 1328.13)
# Stock.create(name: "Alphabet Class A"	                  ,symbol: "GOOGL"	    ,price: 1326.96)
# Stock.create(name: "Hasbro Inc"	                          ,symbol: "HAS"        ,price: 100.31)
# Stock.create(name: "Henry Schein Inc"	                  ,symbol: "HSIC"	    ,price: 69.17)
# Stock.create(name: "Illumina Inc"	                      ,symbol: "ILMN"	    ,price: 319.81)
# Stock.create(name: "Incyte Corp"	                      ,symbol: "INCY"	    ,price: 93.99)
# Stock.create(name: "Intel Corp"	                          ,symbol: "INTC"	    ,price: 56.08)
# Stock.create(name: "Intuit Inc"	                          ,symbol: "INTU"	    ,price: 253.78)
# Stock.create(name: "Intuitive Surgical Inc"	              ,symbol: "ISRG"	    ,price: 580.81)
# Stock.create(name: "IDEXX Laboratories Inc"	              ,symbol: "IDXX"	    ,price: 251.86)
# Stock.create(name: "J.B. Hunt Transport Services Inc"	  ,symbol: "JBHT"	    ,price: 113.46)
# Stock.create(name: "JD.com Inc"	                          ,symbol: "JD"         ,price: 32.54)
# Stock.create(name: "KLA Corp"	                          ,symbol: "KLAC"	    ,price: 161.5)
# Stock.create(name: "Kraft Heinz Co"	                      ,symbol: "KHC"        ,price: 31.25)
# Stock.create(name: "Lam Research Corp"	                  ,symbol: "LRCX"	    ,price: 264.82)
# Stock.create(name: "Liberty Global PLC"	                  ,symbol: "LBTYA"	    ,price: 22.21)
# Stock.create(name: "Liberty Global PLC"	                  ,symbol: "LBTYK"	    ,price: 21.11)
# Stock.create(name: "Lululemon Athletica Inc"	          ,symbol: "LULU"	    ,price: 230.79)
# Stock.create(name: "Mercadolibre Inc"	                  ,symbol: "MELI"	    ,price: 578.52)
# Stock.create(name: "Marriott International Inc"	          ,symbol: "MAR"        ,price: 140.3)
# Stock.create(name: "Microchip Technology Inc"	          ,symbol: "MCHP"	    ,price: 96.71)
# Stock.create(name: "Mondelez International Inc"	          ,symbol: "MDLZ"	    ,price: 53.81)
# Stock.create(name: "Monster Beverage Corp"	              ,symbol: "MNST"	    ,price: 59.92)
# Stock.create(name: "Microsoft Corp"	                      ,symbol: "MSFT"	    ,price: 149.93)
# Stock.create(name: "Micron Technology Inc"	              ,symbol: "MU"         ,price: 46.62)
# Stock.create(name: "Maxim Integrated Products Inc"	      ,symbol: "MXIM"	    ,price: 56.74)
# Stock.create(name: "Mylan NV"	                          ,symbol: "MYL"        ,price: 18.9)
# Stock.create(name: "NetApp Inc"	                          ,symbol: "NTAP"	    ,price: 60.08)
# Stock.create(name: "Netflix Inc"	                      ,symbol: "NFLX"	    ,price: 302.86)
# Stock.create(name: "NetEase Inc"	                      ,symbol: "NTES"	    ,price: 314.2)
# Stock.create(name: "NVIDIA Corp"	                      ,symbol: "NVDA"	    ,price: 208.74)
# Stock.create(name: "NXP Semiconductors NV"	              ,symbol: "NXPI"	    ,price: 117.11)
# Stock.create(name: "O Reilly Automotive Inc"	          ,symbol: "ORLY"	    ,price: 441.04)
# Stock.create(name: "Paychex Inc"	                      ,symbol: "PAYX"	    ,price: 84.42)
# Stock.create(name: "Paccar Inc"	                          ,symbol: "PCAR"	    ,price: 80.11)
# Stock.create(name: "Booking Holdings Inc"	              ,symbol: "BKNG"	    ,price: 1904.22)
# Stock.create(name: "PayPal Holdings Inc"	              ,symbol: "PYPL"	    ,price: 104.59)
# Stock.create(name: "PepsiCo Inc"	                      ,symbol: "PEP"        ,price: 136.34)
# Stock.create(name: "Qualcomm Inc"	                      ,symbol: "QCOM"	    ,price: 82.585)
# Stock.create(name: "Regeneron Pharmaceuticals Inc"	      ,symbol: "REGN"	    ,price: 368.34)
# Stock.create(name: "Ross Stores Inc"	                  ,symbol: "ROST"	    ,price: 113.49)
# Stock.create(name: "Sirius XM Holdings Inc"	              ,symbol: "SIRI"	    ,price: 6.86)
# Stock.create(name: "Skyworks Solutions Inc"	              ,symbol: "SWKS"	    ,price: 99.98)
# Stock.create(name: "Starbucks Corp"	                      ,symbol: "SBUX"	    ,price: 84.45)
# Stock.create(name: "NortonLifeLock Inc"	                  ,symbol: "NLOK"	    ,price: 25.49)
# Stock.create(name: "Synopsys Inc"	                      ,symbol: "SNPS"	    ,price: 131.88)
# Stock.create(name: "Take-Two Interactive Software Inc"	  ,symbol: "TTWO"	    ,price: 123.97)
# Stock.create(name: "Tesla Inc"	                          ,symbol: "TSLA"	    ,price: 330.37)
# Stock.create(name: "Texas Instruments Inc"	              ,symbol: "TXN"        ,price: 120.74)
# Stock.create(name: "T-Mobile US Inc"	                  ,symbol: "TMUS"	    ,price: 76.94)
# Stock.create(name: "Ulta Beauty Inc"	                  ,symbol: "ULTA"	    ,price: 236.02)
# Stock.create(name: "United Airlines Holdings Inc"	      ,symbol: "UAL"        ,price: 87.86)
# Stock.create(name: "Verisign Inc"	                      ,symbol: "VRSN"	    ,price: 185.57)
# Stock.create(name: "Verisk Analytics Inc"	              ,symbol: "VRSK"	    ,price: 146.02)
# Stock.create(name: "Vertex Pharmaceuticals Inc"	          ,symbol: "VRTX"	    ,price: 223.07)
# Stock.create(name: "Walgreens Boots Alliance Inc"	      ,symbol: "WBA"        ,price: 59.1)
# Stock.create(name: "Western Digital Corp"	              ,symbol: "WDC"        ,price: 47.39)
# Stock.create(name: "Workday Inc"	                      ,symbol: "WDAY"	    ,price: 160.97)
# Stock.create(name: "Wynn Resorts Ltd"	                  ,symbol: "WYNN"	    ,price: 118.27)
# Stock.create(name: "Xcel Energy Inc"	                  ,symbol: "XEL"        ,price: 62.14)
# Stock.create(name: "Xilinx Inc"	                          ,symbol: "XLNX"	    ,price: 90.67)

Stock.create(name: "Activision Blizzard Inc"	          ,symbol: "ATVI"	    ,price: 57.99)
Stock.create(name: "Adobe Inc"	                          ,symbol: "ADBE"	    ,price: 310.03)
Stock.create(name: "Advanced Micro Devices Inc"	          ,symbol: "AMD"	    ,price: 34.62)
Stock.create(name: "Align Technology Inc"	              ,symbol: "ALGN"	    ,price: 260.53)
Stock.create(name: "Alexion Pharmaceuticals Inc"	      ,symbol: "ALXN"	    ,price: 110.42)
Stock.create(name: "Amazon.com Inc"	                      ,symbol: "AMZN"	    ,price: 1770.48)
Stock.create(name: "Amgen Inc"	                          ,symbol: "AMGN"	    ,price: 245.41)
Stock.create(name: "American Airlines Group Inc"	      ,symbol: "AAL"	    ,price: 22.24)
Stock.create(name: "Analog Devices Inc"	                  ,symbol: "ADI"	    ,price: 114.43)
Stock.create(name: "Apple Inc"	                          ,symbol: "AAPL"	    ,price: 269.58)
Stock.create(name: "Applied Materials Inc"	              ,symbol: "AMAT"	    ,price: 52.84)
Stock.create(name: "ASML Holding NV"	                  ,symbol: "ASML"	    ,price: 288.84)
Stock.create(name: "Autodesk Inc"	                      ,symbol: "ADSK"	    ,price: 190.63)
Stock.create(name: "Automatic Data Processing Inc"	      ,symbol: "ADP"        ,price: 154.36)
Stock.create(name: "Broadcom Inc"	                      ,symbol: "AVGO"	    ,price: 313.19)
Stock.create(name: "Baidu Inc"	                          ,symbol: "BIDU"	    ,price: 119.75)
Stock.create(name: "Biogen Inc"	                          ,symbol: "BIIB"	    ,price: 289.39)
Stock.create(name: "Biomarin Pharmaceutical Inc"	      ,symbol: "BMRN"	    ,price: 82.08)
Stock.create(name: "Cadence Design Systems Inc"	          ,symbol: "CDNS"	    ,price: 61.81)
Stock.create(name: "Cerner Corp"	                      ,symbol: "CERN"	    ,price: 74.77)
Stock.create(name: "Check Point Software Technologies Ltd",symbol:	"CHKP"	    ,price: 133.31)
Stock.create(name: "Charter Communications Inc"	          ,symbol: "CHTR"	    ,price: 45.27)
Stock.create(name: "Trip.com Group Ltd"	                  ,symbol: "TCOM"	    ,price: 39.22)
Stock.create(name: "Cintas Corp"	                      ,symbol: "CTAS"	    ,price: 224.7)
Stock.create(name: "Cisco Systems Inc"	                  ,symbol: "CSCO"	    ,price: 45.52)
Stock.create(name: "Citrix Systems Inc"	                  ,symbol: "CTXS"	    ,price: 115.78)
Stock.create(name: "Comcast Corp"	                      ,symbol: "CMCSA"	    ,price: 42.04)
Stock.create(name: "Costco Wholesale Corp"	              ,symbol: "COST"	    ,price: 263.1)
Stock.create(name: "CSX Corp"	                          ,symbol: "CSX"        ,price: 78.65)
Stock.create(name: "Cognizant Technology Solutions Corp"  ,symbol:	"CTSH"	    ,price: 62.21)
Stock.create(name: "Dollar Tree Inc"                      ,symbol: "DLTR"	    ,price: 91.8)
Stock.create(name: "Electronic Arts"	                  ,symbol: "EA"         ,price: 162.12)
Stock.create(name: "eBay Inc"	                          ,symbol: "EBAY"	    ,price: 37.79)
Stock.create(name: "Expedia Group Inc"	                  ,symbol: "EXPE"	    ,price: 175.68)
Stock.create(name: "Fastenal Co"	                      ,symbol: "FAST"	    ,price: 39.28)
Stock.create(name: "Facebook"	                          ,symbol: "FB"         ,price: 197.36)
Stock.create(name: "Fiserv Inc"	                          ,symbol: "FISV"	    ,price: 119.79)
Stock.create(name: "Gilead Sciences Inc"	              ,symbol: "GILD"	    ,price: 62.93)
Stock.create(name: "Alphabet Class C"	                  ,symbol: "GOOG"	    ,price: 1325.13)
Stock.create(name: "Alphabet Class A"	                  ,symbol: "GOOGL"	    ,price: 1356.96)
Stock.create(name: "Hasbro Inc"	                          ,symbol: "HAS"        ,price: 106.31)
Stock.create(name: "Henry Schein Inc"	                  ,symbol: "HSIC"	    ,price: 63.17)
Stock.create(name: "Illumina Inc"	                      ,symbol: "ILMN"	    ,price: 316.81)
Stock.create(name: "Incyte Corp"	                      ,symbol: "INCY"	    ,price: 99.99)
Stock.create(name: "Intel Corp"	                          ,symbol: "INTC"	    ,price: 46.08)
Stock.create(name: "Intuit Inc"	                          ,symbol: "INTU"	    ,price: 263.78)
Stock.create(name: "Intuitive Surgical Inc"	              ,symbol: "ISRG"	    ,price: 588.81)
Stock.create(name: "IDEXX Laboratories Inc"	              ,symbol: "IDXX"	    ,price: 253.86)
Stock.create(name: "J.B. Hunt Transport Services Inc"	  ,symbol: "JBHT"	    ,price: 118.46)
Stock.create(name: "JD.com Inc"	                          ,symbol: "JD"         ,price: 39.54)
Stock.create(name: "KLA Corp"	                          ,symbol: "KLAC"	    ,price: 163.5)
Stock.create(name: "Kraft Heinz Co"	                      ,symbol: "KHC"        ,price: 41.25)
Stock.create(name: "Lam Research Corp"	                  ,symbol: "LRCX"	    ,price: 274.82)
Stock.create(name: "Liberty Global PLC"	                  ,symbol: "LBTYA"	    ,price: 21.21)
Stock.create(name: "Liberty Global PLC"	                  ,symbol: "LBTYK"	    ,price: 29.11)
Stock.create(name: "Lululemon Athletica Inc"	          ,symbol: "LULU"	    ,price: 220.79)
Stock.create(name: "Mercadolibre Inc"	                  ,symbol: "MELI"	    ,price: 576.52)
Stock.create(name: "Marriott International Inc"	          ,symbol: "MAR"        ,price: 180.3)
Stock.create(name: "Microchip Technology Inc"	          ,symbol: "MCHP"	    ,price: 98.71)
Stock.create(name: "Mondelez International Inc"	          ,symbol: "MDLZ"	    ,price: 52.81)
Stock.create(name: "Monster Beverage Corp"	              ,symbol: "MNST"	    ,price: 58.92)
Stock.create(name: "Microsoft Corp"	                      ,symbol: "MSFT"	    ,price: 139.93)
Stock.create(name: "Micron Technology Inc"	              ,symbol: "MU"         ,price: 47.62)
Stock.create(name: "Maxim Integrated Products Inc"	      ,symbol: "MXIM"	    ,price: 52.74)
Stock.create(name: "Mylan NV"	                          ,symbol: "MYL"        ,price: 19.9)
Stock.create(name: "NetApp Inc"	                          ,symbol: "NTAP"	    ,price: 63.08)
Stock.create(name: "Netflix Inc"	                      ,symbol: "NFLX"	    ,price: 312.86)
Stock.create(name: "NetEase Inc"	                      ,symbol: "NTES"	    ,price: 344.2)
Stock.create(name: "NVIDIA Corp"	                      ,symbol: "NVDA"	    ,price: 218.74)
Stock.create(name: "NXP Semiconductors NV"	              ,symbol: "NXPI"	    ,price: 147.11)
Stock.create(name: "O Reilly Automotive Inc"	          ,symbol: "ORLY"	    ,price: 442.04)
Stock.create(name: "Paychex Inc"	                      ,symbol: "PAYX"	    ,price: 89.42)
Stock.create(name: "Paccar Inc"	                          ,symbol: "PCAR"	    ,price: 82.11)
Stock.create(name: "Booking Holdings Inc"	              ,symbol: "BKNG"	    ,price: 1914.22)
Stock.create(name: "PayPal Holdings Inc"	              ,symbol: "PYPL"	    ,price: 106.59)
Stock.create(name: "PepsiCo Inc"	                      ,symbol: "PEP"        ,price: 146.34)
Stock.create(name: "Qualcomm Inc"	                      ,symbol: "QCOM"	    ,price: 83.585)
Stock.create(name: "Regeneron Pharmaceuticals Inc"	      ,symbol: "REGN"	    ,price: 378.34)
Stock.create(name: "Ross Stores Inc"	                  ,symbol: "ROST"	    ,price: 112.49)
Stock.create(name: "Sirius XM Holdings Inc"	              ,symbol: "SIRI"	    ,price: 8.86)
Stock.create(name: "Skyworks Solutions Inc"	              ,symbol: "SWKS"	    ,price: 92.98)
Stock.create(name: "Starbucks Corp"	                      ,symbol: "SBUX"	    ,price: 87.45)
Stock.create(name: "NortonLifeLock Inc"	                  ,symbol: "NLOK"	    ,price: 29.49)
Stock.create(name: "Synopsys Inc"	                      ,symbol: "SNPS"	    ,price: 132.88)
Stock.create(name: "Take-Two Interactive Software Inc"	  ,symbol: "TTWO"	    ,price: 173.97)
Stock.create(name: "Tesla Inc"	                          ,symbol: "TSLA"	    ,price: 333.37)
Stock.create(name: "Texas Instruments Inc"	              ,symbol: "TXN"        ,price: 122.74)
Stock.create(name: "T-Mobile US Inc"	                  ,symbol: "TMUS"	    ,price: 75.94)
Stock.create(name: "Ulta Beauty Inc"	                  ,symbol: "ULTA"	    ,price: 236.02)
Stock.create(name: "United Airlines Holdings Inc"	      ,symbol: "UAL"        ,price: 86.86)
Stock.create(name: "Verisign Inc"	                      ,symbol: "VRSN"	    ,price: 195.57)
Stock.create(name: "Verisk Analytics Inc"	              ,symbol: "VRSK"	    ,price: 142.02)
Stock.create(name: "Vertex Pharmaceuticals Inc"	          ,symbol: "VRTX"	    ,price: 243.07)
Stock.create(name: "Walgreens Boots Alliance Inc"	      ,symbol: "WBA"        ,price: 58.1)
Stock.create(name: "Western Digital Corp"	              ,symbol: "WDC"        ,price: 43.39)
Stock.create(name: "Workday Inc"	                      ,symbol: "WDAY"	    ,price: 168.97)
Stock.create(name: "Wynn Resorts Ltd"	                  ,symbol: "WYNN"	    ,price: 113.27)
Stock.create(name: "Xcel Energy Inc"	                  ,symbol: "XEL"        ,price: 65.14)
Stock.create(name: "Xilinx Inc"	                          ,symbol: "XLNX"	    ,price: 80.67)